filebeat.inputs:
- type: log
  paths:
    - /usr/share/filebeat/logs/*.log

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]

logging.metrics.period: 10s
logging.metrics.enabled: true
http.enabled: true
http.host: 0.0.0.0
