filebeat.autodiscover:
  providers:
    - type: docker
      templates:
        - condition:
            contains:
              docker.container.name: wxclientcloud
          config:
            - type: container
              paths:
                - /usr/share/filebeat/logs/${data.docker.container.id}/*.log
              fields:
                service: wxclientcloud
              fields_under_root: true

output.kafka:
  hosts: ["10.106.66.1:9092", "10.106.66.2:9092", "10.106.66.3:9092"]
  topic: "beat-%{[service]}-stdout"