filebeat.inputs:
- type: log
  paths:
    - /usr/share/filebeat/logs/*.log

setup.template.name: "filebeat"
setup.template.pattern: "filebeat-*"
logging.level: debug

#output.elasticsearch:
#  hosts: ["http://elasticsearch:9200"]
#  index: "filebeat-%{[agent.version]}-%{+yyyy.MM.dd}"

output.logstash:
  hosts: ["logstash:5044"]