version: '2.2'
services:
  cerebro:
    image: lmenezes/cerebro:latest
    container_name: cerebro
    ports:
      - "9000:9000"
    command:
      - -Dhosts.0.host=http://elasticsearch:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:7.4.2
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      #- I18N_LOCALE=zh-CN
      - XPACK_GRAPH_ENABLED=true
      - TIMELION_ENABLED=true
      - XPACK_MONITORING_COLLECTION_ENABLED="true"
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  elasticsearch:
    image: elasticsearch:7.4.2
    container_name: es_01
    environment:
      - cluster.name=duanyifei
      - node.name=es_01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - discovery.seed_hosts=es_01,es_02
      - cluster.initial_master_nodes=es_01,es_02
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  elasticsearch2:
    image: elasticsearch:7.4.2
    container_name: es_02
    environment:
      - cluster.name=duanyifei
      - node.name=es_02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - discovery.seed_hosts=es_01,es_02
      - cluster.initial_master_nodes=es_01,es_02
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata2:/usr/share/elasticsearch/data

  metricbeat:
    image: docker.elastic.co/beats/metricbeat:7.4.2
    container_name: metricbeat
    user: root
    environment:
      - output.elasticsearch.hosts=["elasticsearch:9200"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /proc:/hostfs/proc:ro
      - /:/hostfs:ro

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local

