version: '2.2'
services:
  web:
    image: nginx:latest
    volumes:
      # main config path
      - ./nginx.conf/:/etc/nginx/nginx.conf:ro
      # vhosts path
      - ./conf.d/:/etc/nginx/conf.d/
      # file path
      - ./html/:/usr/share/nginx/html/
      # log path
      - ../elk/filebeat/sample_log/:/var/log/nginx/
    command: [nginx-debug, '-g', 'daemon off;']
    ports:
      - 8888:80