version: '2.2'
services:
  elasticsearch:
    image: elasticsearch:7.4.2
    volumes:
      - es01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elk

  filebeat:
    image: store/elastic/filebeat:7.4.2
    command: filebeat -e -strict.perms=false
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./filebeat/sample_log:/usr/share/filebeat/logs/
    networks:
      - elk
    depends_on:
      - elasticsearch
      - logstash
    links:
      - elasticsearch
      - logstash

  kibana:
    image: docker.elastic.co/kibana/kibana:7.4.2
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
#      - I18N_LOCALE=zh-CN
      - XPACK_GRAPH_ENABLED=true
      - TIMELION_ENABLED=true
      - XPACK_MONITORING_COLLECTION_ENABLED="true"
    ports:
      - 5601:5601
    networks:
      - elk
    depends_on:
      - elasticsearch
    links:
      - elasticsearch

  logstash:
    image: logstash:7.4.2
    user: root
    command: logstash --config.reload.automatic
    environment:
      - LOG_LEVEL=debug
      - XPACK_MONITORING_ENABLED=true
    volumes:
      # pipeline config
      - ./logstash/pipeline/:/usr/share/logstash/pipeline/
      # setting config
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      # 将处理数据挂载出来
      - ./logstash/data/:/usr/share/logstash/data/
    networks:
      - elk
    depends_on:
      - elasticsearch
    links:
      - elasticsearch

volumes:
  es01:
    driver: local

networks:
  elk:
    driver: bridge
