version: '2.2'
services:
  filebeat:
    image: store/elastic/filebeat:7.4.2
    user: root
    command: filebeat -e -strict.perms=false
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./filebeat/sample_log/:/usr/share/filebeat/logs/

  elasticsearch:
    image: elasticsearch:7.4.2
    user: root
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1