version: '2.2'
services:
  filebeat:
    image: store/elastic/filebeat:7.4.2
    user: root
    command: filebeat -e -strict.perms=false
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./filebeat/sample_log/:/usr/share/filebeat/logs/
    depends_on:
      - elasticsearch
    networks:
      - es7net

  elasticsearch:
    image: elasticsearch:7.4.2
    container_name: es_01
    user: root
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - node.name=es_01
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - discovery.seed_hosts=es_01,es_02
      - cluster.initial_master_nodes=es_01,es_02
    volumes:
      - ./elasticsearch/backups/:/usr/share/elasticsearch/backups/
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/esdata1/:/usr/share/elasticsearch/data/
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - es7net

  elasticsearch2:
    image: elasticsearch:7.4.2
    container_name: es_02
    user: root
    environment:
      - node.name=es_02
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - discovery.seed_hosts=es_01,es_02
      - cluster.initial_master_nodes=es_01,es_02
    volumes:
      - ./elasticsearch/backups/:/usr/share/elasticsearch/backups/
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/esdata2/:/usr/share/elasticsearch/data/
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - es7net

  kibana:
    image: docker.elastic.co/kibana/kibana:7.4.2
    container_name: kibana7
    environment:
            #      - ELASTICSEARCH_URL=http://elasticsearch:9200
#      - I18N_LOCALE=zh-CN
      - XPACK_GRAPH_ENABLED=true
      - TIMELION_ENABLED=true
      - XPACK_MONITORING_COLLECTION_ENABLED="true"
    ports:
      - 5601:5601
    networks:
      - es7net

networks:
  es7net:
    driver: bridge