version: '2.2'
services:
  filebeat:
    image: store/elastic/filebeat:7.4.2
    user: root
    command: filebeat -e -strict.perms=false
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./filebeat/sample_log/:/usr/share/filebeat/logs/
    depends_on:
      - elasticsearch

  elasticsearch:
    image: elasticsearch:7.4.2
    user: root
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    image: docker.elastic.co/kibana/kibana:7.4.2
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
#      - I18N_LOCALE=zh-CN
      - XPACK_GRAPH_ENABLED=true
      - TIMELION_ENABLED=true
      - XPACK_MONITORING_COLLECTION_ENABLED="true"
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    links:
      - elasticsearch