global:
  scrape_interval:     15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets:
        - 'localhost:9090'

  - job_name: 'flow-exporter'
    scrape_interval: 5s
    static_configs:
      - targets:
        - 'flow-exporter:9590'


  - job_name: 'node-exporter'
    static_configs:
      - targets:
        - '192.168.136.17:9100'